/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista.menuLider;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import java.util.Calendar;
import java.util.TimeZone;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonzales
 */
public class CrearTarea extends javax.swing.JPanel {

    Coordinador coordinador;
    Usuario lider;
    DefaultListModel miembros;
    Grupo grupo;

    public CrearTarea() {
        initComponents();
        miembros = new DefaultListModel();
        jListResponsable.setModel(miembros);
        jTADetallesResponsable.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAddTarea = new javax.swing.JLabel();
        jTFNombreTarea = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jLNombreTarea = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListResponsable = new javax.swing.JList<>();
        jLResponsable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTADetallesResponsable = new javax.swing.JTextArea();
        jBVolver = new javax.swing.JButton();
        jBDetallesResponsable = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jSHora = new javax.swing.JSpinner();
        jSMinuto = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLMinuto = new javax.swing.JLabel();
        jDCFecha = new com.toedter.calendar.JDateChooser();

        jLAddTarea.setText("Crear Tarea");

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jLNombreTarea.setText("Nombre:");

        jLDescripcion.setText("Descripción:");

        jScrollPane2.setViewportView(jListResponsable);

        jLResponsable.setText("Responsable:");

        jTADetallesResponsable.setColumns(20);
        jTADetallesResponsable.setRows(5);
        jScrollPane3.setViewportView(jTADetallesResponsable);

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBDetallesResponsable.setText("Detalles");
        jBDetallesResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetallesResponsableActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha de entrega:");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jSHora.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jSMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText("Hora:");

        jLMinuto.setText("Min:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBGuardar)
                        .addGap(42, 42, 42)
                        .addComponent(jBLimpiar)
                        .addGap(258, 258, 258))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBVolver)
                                .addGap(263, 263, 263)
                                .addComponent(jLAddTarea))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLDescripcion))
                                    .addComponent(jLResponsable, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBDetallesResponsable, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLNombreTarea)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTFNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLMinuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jLAddTarea))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreTarea)
                    .addComponent(jTFNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLResponsable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDetallesResponsable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescripcion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLMinuto)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBLimpiar))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        limpiar();

        coordinador.cargarPanel(4, lider);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBDetallesResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetallesResponsableActionPerformed
        if (jListResponsable.getSelectedValue() != null) {
            jTADetallesResponsable.setText(coordinador.getLogica().getUsuarios().acceder(jListResponsable.getSelectedValue()).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un usuario");
        }
    }//GEN-LAST:event_jBDetallesResponsableActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Calendar c = Calendar.getInstance();
        if (jTFNombreTarea.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre de la tarea");
        } else if (!coordinador.getLogica().validarNombreTarea(jTFNombreTarea.getText(), grupo.getNombre())) {
            JOptionPane.showMessageDialog(null, "Ingrese otro nombre para la tarea");
        } else if (jListResponsable.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un responsable");
        } else if (jTADescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor escriba la descripcion de la tarea");
        } else if (jDCFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor selecione una fecha");
        } else {
            Usuario responsable = coordinador.getLogica().getUsuarios().acceder(jListResponsable.getSelectedValue());
            Calendar fEntrega = jDCFecha.getCalendar();
            fEntrega.set(Calendar.HOUR, (int) jSHora.getValue());
            fEntrega.set(Calendar.MINUTE, (int) jSMinuto.getValue());
            if (fEntrega.compareTo(c) != 1) {
                JOptionPane.showMessageDialog(null, "Seleccione una fecha valida");
            } else {
                Tarea tarea = new Tarea(jTFNombreTarea.getText(), jTADescripcion.getText(), responsable, fEntrega);
                grupo.agregarTarea(tarea);
                JOptionPane.showMessageDialog(null, jTFNombreTarea.getText() + " creada con éxito");
                coordinador.getLogica().escribirListas();
                limpiar();
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetallesResponsable;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBVolver;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLAddTarea;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLMinuto;
    private javax.swing.JLabel jLNombreTarea;
    private javax.swing.JLabel jLResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListResponsable;
    private javax.swing.JSpinner jSHora;
    private javax.swing.JSpinner jSMinuto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextArea jTADetallesResponsable;
    private javax.swing.JTextField jTFNombreTarea;
    // End of variables declaration//GEN-END:variables

    public void llenarJListMiembros(Coordinador c, Usuario l) {
        miembros.removeAllElements();
        int i = 0;
        LIntegrantes u = c.getLogica().getGrupos().accederM(l).getListIntegrantes();
        while (u.accederP(i) != null) {
            miembros.addElement(u.accederP(i).getUserName());
            i++;
        }
    }

    public void limpiar() {
        jTFNombreTarea.setText("");
        jTADescripcion.setText("");
        jTADetallesResponsable.setText("");
        jDCFecha.setDate(null);
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    public void setLider(Usuario l) {
        lider = l;
        grupo = coordinador.getLogica().getGrupos().accederM(l);
    }
}
