/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista.menuLider;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import desCalendar.controlador.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonzales
 */
public class EditarGrupo extends javax.swing.JPanel {

    private Coordinador coordinador;
    private Usuario lider;
    DefaultListModel miembros;

    public EditarGrupo() {
        initComponents();
        miembros = new DefaultListModel();
        jListMiembros.setModel(miembros);
        jTADetalles.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombreGrupo = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jLLider = new javax.swing.JLabel();
        jCBLider = new javax.swing.JComboBox<>();
        jLMiembros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMiembros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADetalles = new javax.swing.JTextArea();
        jBEliminar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBDetalles = new javax.swing.JButton();
        jBEliminarG = new javax.swing.JButton();

        jLNombreGrupo.setText("Nombre Grupo");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLNombre.setText("Nombre:");

        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });

        jLLider.setText("Lider:");

        jLMiembros.setText("Miembros:");

        jScrollPane1.setViewportView(jListMiembros);

        jTADetalles.setColumns(20);
        jTADetalles.setRows(5);
        jScrollPane2.setViewportView(jTADetalles);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBDetalles.setText("Detalles");
        jBDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetallesActionPerformed(evt);
            }
        });

        jBEliminarG.setText("Eliminar Grupo");
        jBEliminarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBEliminar)
                                .addComponent(jLMiembros))
                            .addComponent(jBDetalles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLLider)
                                    .addComponent(jLNombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBVolver)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombreGrupo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jCBLider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBGuardar)
                .addGap(18, 18, 18)
                .addComponent(jBLimpiar)
                .addGap(18, 18, 18)
                .addComponent(jBEliminarG)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBVolver)
                    .addComponent(jLNombreGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLider)
                    .addComponent(jCBLider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLMiembros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEliminar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLimpiar)
                    .addComponent(jBGuardar)
                    .addComponent(jBEliminarG))
                .addGap(88, 88, 88))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        coordinador.cargarPanel(4, lider);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetallesActionPerformed

        jTADetalles.setText(coordinador.getLogica().getGrupos().accederM(lider).getListIntegrantes().acceder(jListMiembros.getSelectedValue().toString()).toString());
    }//GEN-LAST:event_jBDetallesActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTFNombre.setText("");
        jTADetalles.setText("");
        jCBLider.setSelectedItem(null);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        Grupo g = coordinador.getLogica().getGrupos().accederM(lider);
        if (g.getLider() == g.getListIntegrantes().acceder(jListMiembros.getSelectedValue())) {
            JOptionPane.showMessageDialog(null, "No es posible eliminar al lider");
        } else {
            g.getListIntegrantes().eliminar2(jListMiembros.getSelectedValue());
            JOptionPane.showMessageDialog(null, "Eliminado con exito");
            actualizar();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Grupo g = coordinador.getLogica().getGrupos().accederM(lider);
        if (jTFNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el nombre del grupo");
        } else if (jCBLider.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, selecciona un lider");
        } else if (!g.getNombre().equals(jTFNombre.getText())) {
            if (coordinador.getLogica().getGrupos().existe(jTFNombre.getText())) {
                JOptionPane.showMessageDialog(null, "El nombre del grupo ya existe");
            }
        }
        Usuario u = g.getListIntegrantes().acceder(jCBLider.getSelectedItem().toString());
        u.setLider(true);
        g.setLider(u);
        lider.setLider(false);
        lider = u;
        actualizar();
        g.setNombre(jTFNombre.getText());

        JOptionPane.showMessageDialog(null, "Actualizado con éxito");
        coordinador.getLogica().escribirListas();
        coordinador.cargarPanel(4, lider);

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jBEliminarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarGActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "¿Seguro quiere eliminar este grupo?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (res == JOptionPane.YES_OPTION) {
            Grupo g=coordinador.getLogica().getGrupos().accederM(lider);
            coordinador.getLogica().eliminarGrupo(coordinador.getLogica().getGrupos(),coordinador.getLogica().getUsuarios(), g);
            JOptionPane.showMessageDialog(null, "Eliminado con exito");
            coordinador.cargarPanel(1, lider);
        }

    }//GEN-LAST:event_jBEliminarGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalles;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBEliminarG;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBLider;
    private javax.swing.JLabel jLLider;
    private javax.swing.JLabel jLMiembros;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombreGrupo;
    private javax.swing.JList<String> jListMiembros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADetalles;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables

    public void llenarJListMiembros(Coordinador c, Usuario lider) {
        miembros.removeAllElements();
        int i = 0;
        LIntegrantes u = c.getLogica().getGrupos().accederM(lider).getListIntegrantes();
        while (u.accederP(i) != null) {
            miembros.addElement(u.accederP(i).getUserName());
            i++;
        }
    }
    
    public void reinicio(){
        jCBLider.removeAllItems();
        jListMiembros.removeAll();
        jTADetalles.setText("");
        jTFNombre.setText("");
    }
    
    public void llenarJCBLider(Coordinador c, Usuario lider) {
        jCBLider.removeAllItems();
        jCBLider.addItem(lider.getUserName());

        LIntegrantes u = c.getLogica().getGrupos().accederM(lider).getListIntegrantes();
        int i = 0;
        while (u.accederP(i) != null) {
            if (u.accederP(i) != lider) {
                jCBLider.addItem(u.accederP(i).getUserName());
            }
            i++;
        }
    }

    public void actualizar() {
        llenarJCBLider(coordinador, lider);
        llenarJListMiembros(coordinador, lider);
    }

    public void setLider(Usuario l) {
        this.lider = l;
        jLNombreGrupo.setText(coordinador.getLogica().getGrupos().accederM(lider).getNombre());
        jTFNombre.setText(coordinador.getLogica().getGrupos().accederM(lider).getNombre());
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }
}
