/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista.menuLider;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.Grupo;
import descCalendar.modelo.LIntegrantes;
import descCalendar.modelo.LTareas;
import descCalendar.modelo.Tarea;
import descCalendar.modelo.Usuario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonzales
 */
public class EditarTarea extends javax.swing.JPanel {

    Coordinador coordinador;
    Usuario lider;
    DefaultListModel miembros;
    Grupo grupo;

    public EditarTarea() {
        initComponents();
        miembros = new DefaultListModel();
        jListResponsable.setModel(miembros);
        jTADetallesResponsable.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTADetallesResponsable = new javax.swing.JTextArea();
        jLEditarTarea = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jTFNombreTarea = new javax.swing.JTextField();
        jBDetallesResponsable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jLNombreTarea = new javax.swing.JLabel();
        jBLimpiar = new javax.swing.JButton();
        jLDescripcion = new javax.swing.JLabel();
        jSHora = new javax.swing.JSpinner();
        jDCFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListResponsable = new javax.swing.JList<>();
        jSMinuto = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLResponsable = new javax.swing.JLabel();
        jLMinuto = new javax.swing.JLabel();
        jCBTarea = new javax.swing.JComboBox<>();
        jTFNBTarea = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();

        jTADetallesResponsable.setColumns(20);
        jTADetallesResponsable.setRows(5);
        jScrollPane3.setViewportView(jTADetallesResponsable);

        jLEditarTarea.setText("Editar Tarea");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jTFNombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreTareaActionPerformed(evt);
            }
        });

        jBDetallesResponsable.setText("Detalles");
        jBDetallesResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetallesResponsableActionPerformed(evt);
            }
        });

        jTADescripcion.setColumns(20);
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jLabel1.setText("Fecha de entrega:");

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLNombreTarea.setText("Nombre:");

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jLDescripcion.setText("Descripción:");

        jSHora.setModel(new javax.swing.SpinnerNumberModel(1, 1, 24, 1));

        jScrollPane2.setViewportView(jListResponsable);

        jSMinuto.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText("Hora:");

        jLResponsable.setText("Responsable:");

        jLMinuto.setText("Min:");

        jCBTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTareaActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione la tarea:");

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jBGuardar)
                                        .addGap(42, 42, 42)
                                        .addComponent(jBLimpiar)
                                        .addGap(55, 55, 55)
                                        .addComponent(jBEliminar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLNombreTarea)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTFNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSHora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLMinuto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLDescripcion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLResponsable)
                                        .addComponent(jBDetallesResponsable))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jBVolver))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCBTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLEditarTarea)
                                            .addComponent(jTFNBTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBBuscar)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jLEditarTarea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNBTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreTarea)
                    .addComponent(jTFNombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLResponsable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBDetallesResponsable)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLDescripcion)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDCFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLMinuto)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBLimpiar)
                    .addComponent(jBEliminar))
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        limpiar();

        coordinador.cargarPanel(4, lider);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBDetallesResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetallesResponsableActionPerformed
        if (jListResponsable.getSelectedValue() != null) {
            jTADetallesResponsable.setText(coordinador.getLogica().getUsuarios().acceder(jListResponsable.getSelectedValue()).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un usuario");
        }
    }//GEN-LAST:event_jBDetallesResponsableActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        Calendar c = Calendar.getInstance();
        if (jTFNombreTarea.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre de la tarea");
        } else if (!coordinador.getLogica().validarNombreTarea(jTFNombreTarea.getText(), grupo.getNombre())) {
            JOptionPane.showMessageDialog(null, "Ingrese otro nombre para la tarea");
        } else if (jListResponsable.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un responsable");
        } else if (jTADescripcion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor escriba la descripcion de la tarea");
        } else if (jDCFecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Por favor selecione una fecha");
        } else {
            Usuario responsable = coordinador.getLogica().getUsuarios().acceder(jListResponsable.getSelectedValue());
            Calendar fEntrega = jDCFecha.getCalendar();
            fEntrega.set(Calendar.HOUR, (int) jSHora.getValue());
            fEntrega.set(Calendar.MINUTE, (int) jSMinuto.getValue());
            if (fEntrega.compareTo(c) != 1) {
                JOptionPane.showMessageDialog(null, "Seleccione una fecha valida");
            } else {
                Tarea tarea = new Tarea(jTFNombreTarea.getText(), jTADescripcion.getText(), responsable, fEntrega);
                grupo.agregarTarea(tarea);
                JOptionPane.showMessageDialog(null, jTFNombreTarea.getText() + " Actualizada con éxito");
                coordinador.getLogica().escribirListas();
                limpiar();
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        LTareas u = coordinador.getLogica().buscarCoincidenciasTareas(grupo.getListTareas(), jTFNBTarea.getText());
        llenarJCBTarea(u);
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jCBTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTareaActionPerformed
        if (jCBTarea.getSelectedItem() != null) {
            String nTarea = jCBTarea.getSelectedItem().toString();
            llenarCampos(nTarea);
        }
    }//GEN-LAST:event_jCBTareaActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        if (jCBTarea.getSelectedItem() != null) {
            grupo.getListTareas().eliminarNom(jTFNombreTarea.getText());
            coordinador.getLogica().escribirListas();
            JOptionPane.showMessageDialog(null, jTFNombreTarea.getText() + " Eliminado con éxito");
            llenarJCBTarea(coordinador, lider);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTFNombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreTareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBDetallesResponsable;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBTarea;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLEditarTarea;
    private javax.swing.JLabel jLMinuto;
    private javax.swing.JLabel jLNombreTarea;
    private javax.swing.JLabel jLResponsable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListResponsable;
    private javax.swing.JSpinner jSHora;
    private javax.swing.JSpinner jSMinuto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextArea jTADetallesResponsable;
    private javax.swing.JTextField jTFNBTarea;
    private javax.swing.JTextField jTFNombreTarea;
    // End of variables declaration//GEN-END:variables

    public void llenarJListMiembros(Coordinador c, Usuario l) {
        miembros.removeAllElements();
        int i = 0;
        LIntegrantes u = c.getLogica().getGrupos().accederM(l).getListIntegrantes();
        while (u.accederP(i) != null) {
            miembros.addElement(u.accederP(i).getUserName());
            i++;
        }
    }

    public void limpiar() {
        jTFNombreTarea.setText("");
        jTADescripcion.setText("");
        jTADetallesResponsable.setText("");
        jSHora.setValue(1);
        jSMinuto.setValue(0);
        jDCFecha.setCalendar(null);
    }

    public void llenarCampos(String nTarea) {
        jTFNombreTarea.setText(nTarea);
        jTADescripcion.setText(grupo.getListTareas().accederNom(nTarea).getDescripcion());
        Date fEntrega = grupo.getListTareas().accederNom(nTarea).getfEntrega();
        jDCFecha.setDate(fEntrega);
        jSHora.setValue(fEntrega.getHours());
        jSMinuto.setValue(fEntrega.getMinutes());
    }

    public void llenarJCBTarea(Coordinador c, Usuario l) {
        jCBTarea.removeAllItems();

        LTareas u = c.getLogica().getGrupos().accederM(lider).getListTareas();
        int i = 0;
        while (u.accederP(i) != null) {
            jCBTarea.addItem(u.accederP(i).getNombre());
            i++;
        }
    }

    public void llenarJCBTarea(LTareas u) {
        jCBTarea.removeAllItems();
        int i = 0;
        while (u.accederP(i) != null) {
            jCBTarea.addItem(u.accederP(i).getNombre());
            i++;
        }
    }

    public void setLider(Usuario l) {
        lider = l;
        grupo = coordinador.getLogica().getGrupos().accederM(lider);
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

}
