/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista.menuLider;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonzales
 */
public class Invitar extends javax.swing.JPanel{

    DefaultListModel miembros;
    Coordinador coordinador;
    Usuario lider;

    public Invitar() {
        initComponents();
        miembros = new DefaultListModel();
        jListMiembros.setModel(miembros);
        jTADetalles.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLInvitar = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMiembros = new javax.swing.JList<>();
        jBInvitar = new javax.swing.JButton();
        jBDetalles = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADetalles = new javax.swing.JTextArea();

        jLInvitar.setText("Invitar Miembros");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListMiembros);

        jBInvitar.setText("Invitar");
        jBInvitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInvitarActionPerformed(evt);
            }
        });

        jBDetalles.setText("Mostrar detalles");
        jBDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetallesActionPerformed(evt);
            }
        });

        jTADetalles.setColumns(20);
        jTADetalles.setRows(5);
        jScrollPane1.setViewportView(jTADetalles);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVolver)
                .addGap(241, 241, 241)
                .addComponent(jLInvitar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jBInvitar)
                        .addGap(171, 171, 171))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jBDetalles)))))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jLInvitar))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDetalles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(71, 71, 71)
                .addComponent(jBInvitar)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        jTADetalles.setText("");
        coordinador.cargarPanel(4, lider);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBInvitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInvitarActionPerformed
        if (jListMiembros.getSelectedValue() != null) {
            String mensaje = JOptionPane.showInputDialog("Escribe un mensaje");
            try {
                if (mensaje.equals("")) {
                    mensaje = "Únete a mi grupo";
                }
            } catch (Exception e) {
                mensaje = "Únete a mi grupo";
            }
            coordinador.getLogica().invitar(jListMiembros.getSelectedValue().toString(), lider, mensaje);
            JOptionPane.showMessageDialog(null, "Invitacion realizada");
            coordinador.getLogica().escribirListas();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un usuario");
        }
    }//GEN-LAST:event_jBInvitarActionPerformed

    private void jBDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetallesActionPerformed
        if (jListMiembros.getSelectedValue() != null) {
            jTADetalles.setText(coordinador.getLogica().getUsuarios().acceder(jListMiembros.getSelectedValue()).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecciona un usuario");
        }
    }//GEN-LAST:event_jBDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDetalles;
    private javax.swing.JButton jBInvitar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLInvitar;
    private javax.swing.JList<String> jListMiembros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADetalles;
    // End of variables declaration//GEN-END:variables

    public void llenarJListMiembros(Coordinador c) {
        miembros.removeAllElements();
        int i = 0;
        LIntegrantes u = c.getLogica().getUsuarios();
        while (u.accederP(i) != null) {
            miembros.addElement(c.getLogica().nombresMiembro(i));
            i++;
        }
    }


    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    public void setLider(Usuario l) {
        this.lider = l;
    }

}
