/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista.menuLider;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Gonzales
 */
public class MenuLider extends javax.swing.JPanel {

    Coordinador coordinador;
    Usuario lider;
    
    public MenuLider() {
        initComponents();
        
    }
    
    public void setLider(Usuario l){
        this.lider = l;
        jLBienvenida.setText("Bienvenido " + l.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBienvenida = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jBMiPerfil = new javax.swing.JButton();
        jBInvitar = new javax.swing.JButton();
        jBAddTarea = new javax.swing.JButton();
        jBGrupo = new javax.swing.JButton();
        jBEditarTarea = new javax.swing.JButton();
        jBHistorial = new javax.swing.JButton();
        jBTareasPendientes = new javax.swing.JButton();

        jLBienvenida.setText("Bienvenido");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBMiPerfil.setText("Mi perfill");
        jBMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMiPerfilActionPerformed(evt);
            }
        });

        jBInvitar.setText("Invitar miembros");
        jBInvitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInvitarActionPerformed(evt);
            }
        });

        jBAddTarea.setText("Crear tarea");
        jBAddTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddTareaActionPerformed(evt);
            }
        });

        jBGrupo.setText("Editar grupo");
        jBGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGrupoActionPerformed(evt);
            }
        });

        jBEditarTarea.setText("Editar tarea");
        jBEditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarTareaActionPerformed(evt);
            }
        });

        jBHistorial.setText("Tareas realizadas");
        jBHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistorialActionPerformed(evt);
            }
        });

        jBTareasPendientes.setText("Tareas pendientes");
        jBTareasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTareasPendientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVolver)
                        .addGap(222, 222, 222)
                        .addComponent(jLBienvenida))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBTareasPendientes)
                        .addComponent(jBAddTarea)
                        .addComponent(jBInvitar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBHistorial)
                            .addComponent(jBEditarTarea)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBGrupo)
                                .addGap(26, 26, 26)))
                        .addContainerGap(238, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBMiPerfil)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBVolver)
                            .addComponent(jBMiPerfil)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLBienvenida)))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBInvitar)
                    .addComponent(jBGrupo))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAddTarea)
                    .addComponent(jBEditarTarea))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBHistorial)
                    .addComponent(jBTareasPendientes))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        coordinador.cargarPanel(1,null);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMiPerfilActionPerformed
        coordinador.cargarPanel(7, lider);
    }//GEN-LAST:event_jBMiPerfilActionPerformed

    private void jBInvitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInvitarActionPerformed
        coordinador.cargarPanel(8, lider);
    }//GEN-LAST:event_jBInvitarActionPerformed

    private void jBGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGrupoActionPerformed
        coordinador.cargarPanel(9, lider);
    }//GEN-LAST:event_jBGrupoActionPerformed

    private void jBTareasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTareasPendientesActionPerformed
        coordinador.cargarPanel(10, lider);
    }//GEN-LAST:event_jBTareasPendientesActionPerformed

    private void jBAddTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddTareaActionPerformed
        coordinador.cargarPanel(11, lider);
    }//GEN-LAST:event_jBAddTareaActionPerformed

    private void jBHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistorialActionPerformed
        coordinador.cargarPanel(12, lider);
    }//GEN-LAST:event_jBHistorialActionPerformed

    private void jBEditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarTareaActionPerformed
        this.coordinador.cargarPanel(14, lider);
    }//GEN-LAST:event_jBEditarTareaActionPerformed

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddTarea;
    private javax.swing.JButton jBEditarTarea;
    private javax.swing.JButton jBGrupo;
    private javax.swing.JButton jBHistorial;
    private javax.swing.JButton jBInvitar;
    private javax.swing.JButton jBMiPerfil;
    private javax.swing.JButton jBTareasPendientes;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLBienvenida;
    // End of variables declaration//GEN-END:variables
}
