/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import desCalendar.controlador.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author 
 */
public class MostrarMiembros extends javax.swing.JPanel {
    
    private Coordinador coordinador;
    private Usuario us;
    Grupo grupo;
    DefaultListModel miembros;
    /**
     * Creates new form MostrarMiembros
     */
    public MostrarMiembros() {
        initComponents();
        miembros = new DefaultListModel();
        jListMiembros.setModel(miembros);
        jTextADetMiembro.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVolver = new javax.swing.JButton();
        jLMiembros = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMiembros = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextADetMiembro = new javax.swing.JTextArea();
        jLDetallesMiembro = new javax.swing.JLabel();
        jLBuscarMiembro = new javax.swing.JLabel();
        jTextNom = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jLResul = new javax.swing.JLabel();
        jCBResultados = new javax.swing.JComboBox<>();

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLMiembros.setText("Miembros:");

        jListMiembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListMiembrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListMiembros);

        jTextADetMiembro.setColumns(20);
        jTextADetMiembro.setRows(5);
        jScrollPane2.setViewportView(jTextADetMiembro);

        jLDetallesMiembro.setText("Detalles de miembro:");

        jLBuscarMiembro.setText("Buscar miembro (por nombre de usuario):");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLResul.setText("Resultados de busqueda:");

        jCBResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBResultadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBVolver)
                                    .addComponent(jLMiembros))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLDetallesMiembro)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLBuscarMiembro)
                            .addComponent(jLResul)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCBResultados, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMiembros)
                    .addComponent(jLDetallesMiembro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLBuscarMiembro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLResul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        if(us.getUserName().equals(coordinador.getLogica().getGrupos().accederM(us).getLider().getUserName())){
            coordinador.cargarPanel(4, us);
        }else{
            coordinador.cargarPanel(5, us);
        }
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jListMiembrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMiembrosMouseClicked
        jTextADetMiembro.setText("");
        if(!jListMiembros.isSelectionEmpty()){
            jTextADetMiembro.setText(coordinador.getLogica().getGrupos().accederM(us).getListIntegrantes().acceder(jListMiembros.getSelectedValue().toString()).toString());
        }
    }//GEN-LAST:event_jListMiembrosMouseClicked

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if(!jTextNom.getText().equals("")){
            LIntegrantes u = coordinador.getLogica().buscarCoincidenciasMiembros(grupo.getListIntegrantes(), jTextNom.getText());
            llenarJCBMiembro(u);
            llenarJListMiembros(coordinador, us);
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jCBResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBResultadosActionPerformed
        if(jCBResultados.getSelectedItem()!=null){
                jTextADetMiembro.setText("");
                jTextADetMiembro.setText(coordinador.getLogica().getGrupos().accederM(us).getListIntegrantes().acceder(jCBResultados.getSelectedItem().toString()).toString());
        }
    }//GEN-LAST:event_jCBResultadosActionPerformed

    public void llenarJListMiembros(Coordinador c, Usuario usu) {
        miembros.removeAllElements();
        int i = 0;
        LIntegrantes u = c.getLogica().getGrupos().accederM(usu).getListIntegrantes();
        while (u.accederP(i) != null) {
            miembros.addElement(u.accederP(i).getUserName());
            i++;
        }
    }
    
    public void llenarJCBMiembro(LIntegrantes u) {
        jCBResultados.removeAllItems();
        int i = 0;
        while (u.accederP(i) != null) {
            jCBResultados.addItem(u.accederP(i).getUserName());
            i++;
        }
    }
    
    public void actualizar() {
        llenarJListMiembros(coordinador, us);
    }
    
    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }
    
    public void setUsuario(Usuario usu) {
        this.us = usu;
        grupo = coordinador.getLogica().getGrupos().accederM(us);
    }
    
    public void vaciarDetMiembro(){
        jTextADetMiembro.setText("");
        jTextNom.setText("");
        jCBResultados.removeAllItems();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBResultados;
    private javax.swing.JLabel jLBuscarMiembro;
    private javax.swing.JLabel jLDetallesMiembro;
    private javax.swing.JLabel jLMiembros;
    private javax.swing.JLabel jLResul;
    private javax.swing.JList<String> jListMiembros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextADetMiembro;
    private javax.swing.JTextField jTextNom;
    // End of variables declaration//GEN-END:variables
}
