/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 
 */
public class Perfil extends javax.swing.JPanel {

    Coordinador coordinador;
    Usuario us;

    public Perfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTxtUserName = new javax.swing.JTextField();
        jLUserName = new javax.swing.JLabel();
        jTxtDir = new javax.swing.JTextField();
        jLDir = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jLCorreo = new javax.swing.JLabel();
        jPContra = new javax.swing.JPasswordField();
        jLContra = new javax.swing.JLabel();
        jTxtTelf = new javax.swing.JTextField();
        jLTelf = new javax.swing.JLabel();
        jBVolver = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLNombreLider = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jBEliCuenta = new javax.swing.JButton();

        jLNombre.setText("Nombre:");

        jTxtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellidoKeyTyped(evt);
            }
        });

        jLApellido.setText("Apellido:");

        jLUserName.setText("Nombre de usuario:");

        jLDir.setText("Dirección:");

        jLCorreo.setText("Correo:");

        jLContra.setText("Contraseña:");

        jTxtTelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtTelfKeyTyped(evt);
            }
        });

        jLTelf.setText("Celular:");

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLNombreLider.setText("NombreLider");

        jTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombreKeyTyped(evt);
            }
        });

        jBEliCuenta.setText("Elminar Cuenta");
        jBEliCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBVolver)
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jBGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLUserName)
                            .addComponent(jLDir)
                            .addComponent(jLCorreo)
                            .addComponent(jLContra)
                            .addComponent(jLTelf))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtUserName)
                            .addComponent(jTxtDir)
                            .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPContra, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLNombreLider)))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEliCuenta)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jLNombreLider))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jLApellido)
                    .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUserName)
                    .addComponent(jTxtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDir)
                    .addComponent(jTxtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCorreo)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLContra)
                    .addComponent(jPContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLTelf)
                    .addComponent(jTxtTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jBCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jBEliCuenta)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellidoKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isLetter(caracter) && !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtApellidoKeyTyped

    private void jTxtTelfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtTelfKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isDigit(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtTelfKeyTyped

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed

        if (jTxtNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre");
        } else if (jTxtApellido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el apellido");
        } else if (jTxtUserName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el nombre de usuario");
        } else if (jTxtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el correo");
        } else if (jPContra.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese la contraseña");
        } else if (jTxtTelf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el número de celular");
        } else if (!coordinador.getLogica().validarCorreo(jTxtCorreo.getText())) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un correo válido");
        } else if (!coordinador.getLogica().validarTelf(Integer.parseInt(jTxtTelf.getText()))) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un celular válido");
        } else if (!coordinador.getLogica().validarContra(jPContra.getText())) {
            JOptionPane.showMessageDialog(null, "Por favor ingresa una contraseña de tamaño mayor a 4 caracteres, que no contenga simbolos");
        } else if (!coordinador.getLogica().validarNombreUsuario(jTxtUserName.getText()) && !jTxtUserName.getText().equals(us.getUserName())) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe, ingresa otro");
        } else {
            us.setNombre(jTxtNombre.getText());
            us.setApellido(jTxtApellido.getText());
            us.setUserName(jTxtUserName.getText());
            us.setDirec(jTxtDir.getText());
            us.setCorreo(jTxtCorreo.getText());
            us.setContra(jPContra.getText());
            us.setTelf(Integer.parseInt(jTxtTelf.getText()));

            JOptionPane.showMessageDialog(null, "Actualizado con éxito");
            coordinador.getLogica().escribirListas();
            if (us.getLider()) {
                coordinador.cargarPanel(4, us);
            } else {
                coordinador.cargarPanel(5, us);
            }
        }

    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        if (!us.getEstado()) {
            coordinador.cargarPanel(15, us);
        } else {
            if (us.getLider()) {
                coordinador.cargarPanel(4, us);
            } else {
                coordinador.cargarPanel(5, us);
            }
        }
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (!Character.isLetter(caracter) && !Character.isSpaceChar(caracter)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTxtNombreKeyTyped

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        if (!us.getEstado()) {
            coordinador.cargarPanel(15, us);
        } else {
            if (us.getLider()) {
                coordinador.cargarPanel(4, us);
            } else {
                coordinador.cargarPanel(5, us);
            }
        }
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBEliCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliCuentaActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "¿Seguro quiere eliminar esta cuenta?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (!us.getEstado()) {
            if (res == JOptionPane.YES_OPTION) {
                eliminarCuenta(us);
            }
        } else {
            if (res == JOptionPane.YES_OPTION && !us.getUserName().equals(coordinador.getLogica().getGrupos().accederM(us).getLider().getUserName())) {
                eliminarCuenta(us);
            } else {
                if (us.getUserName().equals(coordinador.getLogica().getGrupos().accederM(us).getLider().getUserName())) {
                    JOptionPane.showMessageDialog(null, "Primero seleccione un nuevo lider para el grupo.");
                }
            }
        }
    }//GEN-LAST:event_jBEliCuentaActionPerformed

    public void eliminarCuenta(Usuario usu) {
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel label = new javax.swing.JLabel("¿Seguro quiere eliminar esta cuenta?");
        javax.swing.JPasswordField contr = new javax.swing.JPasswordField(20);
        panel.add(label);
        panel.add(contr);
        String[] opciones = new String[]{"Eliminar", "Cancelar"};
        int ingcontra = JOptionPane.showOptionDialog(null, panel, "Eliminar cuenta", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[1]);
        if (ingcontra == 0) {
            String contra = contr.getText();
            if (contra.equals(usu.getContra())) {
                coordinador.getLogica().getUsuarios().eliminar2(usu.getUserName());
                if (usu.getEstado()) {
                    coordinador.getLogica().getGrupos().accederM(usu).getListIntegrantes().eliminar2(usu.getUserName());
                }
                coordinador.getLogica().escribirListas();
                JOptionPane.showMessageDialog(null, "Cuenta eliminada");
                coordinador.cargarPanel(1, usu);
            } else {
                JOptionPane.showMessageDialog(null, "Contraseña incorrecta");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliCuenta;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLContra;
    private javax.swing.JLabel jLCorreo;
    private javax.swing.JLabel jLDir;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombreLider;
    private javax.swing.JLabel jLTelf;
    private javax.swing.JLabel jLUserName;
    private javax.swing.JPasswordField jPContra;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtDir;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtTelf;
    private javax.swing.JTextField jTxtUserName;
    // End of variables declaration//GEN-END:variables

    public void llenarDatos() {
        jTxtNombre.setText(us.getNombre());
        jTxtApellido.setText(us.getApellido());
        jTxtUserName.setText(us.getUserName());
        jTxtDir.setText(us.getDirec());
        jTxtCorreo.setText(us.getCorreo());
        jPContra.setText(us.getContra());
        jTxtTelf.setText(Integer.toString(us.getTelf()));
    }

    public void setUsuario(Usuario us) {
        this.us = us;
        jLNombreLider.setText(us.getNombre());
        llenarDatos();
    }

    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }
}
