/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descCalendar.vista;

import desCalendar.controlador.Coordinador;
import descCalendar.modelo.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *

 */
public class TareasRealizadas extends javax.swing.JPanel {

    /**
     * Creates new form TareasRealizadas
     */
    Coordinador coordinador;
    Usuario us;
    DefaultComboBoxModel nomTareasRea;
    Grupo grupo;
    
    public TareasRealizadas() {
        initComponents();
        nomTareasRea = new DefaultComboBoxModel();
        jCBTareasRealizadas.setModel(nomTareasRea);
        jTextComentarios.setEditable(false);
        jTTareasSelect.setEditable(false);
        jTextComentarios.setLineWrap(true);
        jTextComentarios.setWrapStyleWord(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVolver = new javax.swing.JButton();
        jLHistorial = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTareasSelect = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextComentarios = new javax.swing.JTextArea();
        jLDetTarea = new javax.swing.JLabel();
        jLComTarea = new javax.swing.JLabel();
        jBBuscar = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jCBTareasRealizadas = new javax.swing.JComboBox<>();
        jBAbrirArchivo = new javax.swing.JButton();
        jTFNombreArchivo = new javax.swing.JTextField();

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLHistorial.setText("Historial");

        jTTareasSelect.setColumns(20);
        jTTareasSelect.setRows(5);
        jScrollPane2.setViewportView(jTTareasSelect);

        jTextComentarios.setColumns(20);
        jTextComentarios.setRows(5);
        jScrollPane3.setViewportView(jTextComentarios);

        jLDetTarea.setText("Detalles de Tarea:");

        jLComTarea.setText("Comentarios de tarea:");

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jCBTareasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTareasRealizadasActionPerformed(evt);
            }
        });

        jBAbrirArchivo.setText("Abrir");
        jBAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAbrirArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscar))
                            .addComponent(jCBTareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDetTarea)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLComTarea)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jBAbrirArchivo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jTFNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBVolver)
                        .addGap(107, 107, 107)
                        .addComponent(jLHistorial)))
                .addGap(21, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVolver)
                    .addComponent(jLHistorial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBTareasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLDetTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLComTarea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTFNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBAbrirArchivo)
                                .addGap(97, 97, 97)))))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        if(us.getLider()){
            coordinador.cargarPanel(4, us);
        }else{
            coordinador.cargarPanel(5, us);
        }
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        if(!jTextBuscar.getText().equals("")){
            if(!jTextBuscar.getText().equals("")){
            LTareas u = coordinador.getLogica().buscarCoincidenciasTareas(grupo.getHistorial(), jTextBuscar.getText());
            llenarJCBTarea(u);
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jCBTareasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTareasRealizadasActionPerformed
        jTTareasSelect.setText("");
        jTextComentarios.setText("");
        
        if(jCBTareasRealizadas.getSelectedItem()!=null){
            Tarea t = grupo.getHistorial().accederNom(jCBTareasRealizadas.getSelectedItem().toString());
            String fichero = t.getFichero();
            jTFNombreArchivo.setText(fichero);
            jTTareasSelect.setText(grupo.getHistorial().accederNom(jCBTareasRealizadas.getSelectedItem().toString()).toString());
            jTextComentarios.setText(grupo.getHistorial().accederNom(jCBTareasRealizadas.getSelectedItem().toString()).toStringComentarios());
        }
    }//GEN-LAST:event_jCBTareasRealizadasActionPerformed

    private void jBAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAbrirArchivoActionPerformed
        try{
            ProcessBuilder pB = new ProcessBuilder();
            pB.command("cmd.exe","/c",jTFNombreArchivo.getText());
            pB.start();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No es posible abrir el archivo");
        }
    }//GEN-LAST:event_jBAbrirArchivoActionPerformed
    
    public void setCoordinador (Coordinador coordinador){
        this.coordinador = coordinador;
    }
    
    public void setUsuario (Usuario u){
        us = u;
        grupo = coordinador.getLogica().getGrupos().accederM(us);
    }
    
    public void reinicio(){
        jTextComentarios.setText("");
        jTTareasSelect.setText("");
        jTextBuscar.setText("");
    }
    
    public void llenarJCBTarea(Coordinador c, Usuario l) {
       jCBTareasRealizadas.removeAllItems();

        LTareas u = c.getLogica().getGrupos().accederM(us).getListTareas();
        int i = 0;
        while (u.accederP(i) != null) {
            jCBTareasRealizadas.addItem(u.accederP(i).getNombre());
            i++;
        }
    }
    
    public void llenarJCBTarea(LTareas u) {
        jCBTareasRealizadas.removeAllItems();
        int i = 0;
        while (u.accederP(i) != null) {
            jCBTareasRealizadas.addItem(u.accederP(i).getNombre());
            i++;
        }
    }
    
    public void actualizarListTareasRea(){
        jCBTareasRealizadas.setModel(coordinador.getLogica().getNomTareasRealizadas(us));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAbrirArchivo;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBTareasRealizadas;
    private javax.swing.JLabel jLComTarea;
    private javax.swing.JLabel jLDetTarea;
    private javax.swing.JLabel jLHistorial;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFNombreArchivo;
    private javax.swing.JTextArea jTTareasSelect;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextArea jTextComentarios;
    // End of variables declaration//GEN-END:variables
}
